### ISSUE TITLE
Get Video Status

### ISSUE THREAD

**Issue by ronny-montano** [prahack/vimeo_player#4]
How to know if the video has reached the end and then mark it as seen?

**Comment by susil07** [comment]
How to know if the video has reached the end ? @prahack @adelarsq

**Comment by adelarsq** [comment]
@susil07 I don't think that is possible, since it's a webview. Maybe some kind a hack around WebView and JavaScript, but I don't think that is productive and/or bug safe.

On this case I recomend you to use another library for videos.
